//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string fecha_registro { get; set; }
        public int id_marca { get; set; }
        public int id_categoria { get; set; }
        public int id_tipo_producto { get; set; }
        public string serial { get; set; }
        public int id_espacio { get; set; }
        public int id_persona { get; set; }
        public bool estado { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_espacio tb_espacio { get; set; }
        public virtual tb_marca tb_marca { get; set; }
        public virtual tb_persona tb_persona { get; set; }
        public virtual tb_tipoProducto tb_tipoProducto { get; set; }
    }
}
